### ISSUE TITLE
npm install出现错误

### ISSUE THREAD

**Issue by Unknow-404** [ix64/unlock-music#90]
G:\Github\UnblockMusic-Client>npm install

> core-js@2.6.11 postinstall G:\Github\UnblockMusic-Client\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@3.6.5 postinstall G:\Github\UnblockMusic-Client\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js-pure@3.6.5 postinstall G:\Github\UnblockMusic-Client\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

> ejs@2.7.4 postinstall G:\Github\UnblockMusic-Client\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1297 packages from 865 contributors and audited 1300 packages in 215.13s

45 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by ix64** [comment]
仔细阅读相应内容，这不是报错，没有报错。

**Comment by ix64** [comment]
请按照Issue Template提交bug报告，此Issue将立即关闭

**Comment by Unknow-404** [comment]
但是编译的时候显示：

G:\Github\unlock-music>npm run build

> unlock-music@1.6.2 build G:\Github\unlock-music
> vue-cli-service build


-  Building for production...Warning (workerize-loader): output.globalObject is set to "window". It should be set to "self" or "this" to support HMR in Workers.
\  Building for production...

 ERROR  Failed to compile with 20 errors                                                                     下午2:26:55

 error  in ./src/App.vue?vue&type=style&index=0&lang=css&

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/App.vue?vue&type=style&index=0&lang=css& 1:0-424 1:440-443 1:445-866 1:445-866
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/base.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 2:0-45 5:0-45 8:0-45 11:0-45 14:0-45 17:0-45 20:0-45 23:0-45 26:0-45 29:0-45 32:0-45 35:0-45 38:0-45 41:0-45 44:0-45 47:0-45 50:0-45 59:0-45
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/notification.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 1:0-73
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/radio.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 10:0-59
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/tooltip.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 7:0-63
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/checkbox.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 13:0-65
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/progress.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 4:0-65
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/row.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 22:0-55
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/icon.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 25:0-57
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/col.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 19:0-55
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/upload.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 16:0-61
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/main.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 34:0-57
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/table-column.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 37:0-72
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/container.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 28:0-67
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/footer.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 31:0-61
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/button.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 43:0-61
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/image.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 46:0-59
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/table.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 40:0-59
 @ multi ./src/main.js

 error  in ./node_modules/element-ui/lib/theme-chalk/link.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/main.js 49:0-57
 @ multi ./src/main.js

 error  in ./src/component/upload.vue?vue&type=style&index=0&id=41f8efc1&scoped=true&lang=css&

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: No valid exports main found for 'G:\Github\unlock-music\node_modules\colorette'

(@G:\Github\unlock-music\postcss.config.js)
    at load (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:28:11)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (G:\Github\unlock-music\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:33:14)
    at G:\Github\unlock-music\node_modules\postcss-load-config\src\index.js:94:14
    at G:\Github\unlock-music\node_modules\webpack\lib\NormalModule.js:316:20
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (G:\Github\unlock-music\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at G:\Github\unlock-music\node_modules\postcss-loader\src\index.js:208:9

 @ ./src/component/upload.vue?vue&type=style&index=0&id=41f8efc1&scoped=true&lang=css& 1:0-469 1:485-488 1:490-956 1:490-956
 @ ./src/component/upload.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unlock-music@1.6.2 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unlock-music@1.6.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-08-16T06_26_56_091Z-debug.log

**Comment by Unknow-404** [comment]
[2020-08-16T06_26_56_091Z-debug.log](https://github.com/ix64/unlock-music/files/5080107/2020-08-16T06_26_56_091Z-debug.log)

**Comment by Unknow-404** [comment]
呃那个Bug报告太难写了。。。直接创建了Issues。。。见谅。

**Comment by Unknow-404** [comment]
这是直接clone下来的源码，没有修改

**Comment by Unknow-404** [comment]
一直是无法编译

**Comment by ix64** [comment]
检查是否内存不足

**Comment by Unknow-404** [comment]
剩余4G以上内存

**Comment by ix64** [comment]
参考GitHub Actions，每一个版本的都是CI自动编译通过的

**Comment by ix64** [comment]
可以尝试清空node_modules，通过npm ci命令安装依赖
